baseURL: 'http://optoutkoplzfgs7wl3gkg5nmtrrs7ki6ljcguf7c4w7rdsrtozlghxad.onion/'
publishDir: tor
title: Opt Out Podcast
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Opt Out Podcast
  description: "Welcome to Opt Out, the podcast focused on helping you opt out of surveillance capitalism and learn more about how you can take back your privacy + data-sovereignty."
  author: Seth For Privacy
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  images:
    - /images/og-image.png

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  mainSections: episodes

  assets:
    disableHLJS: true
    # disableFingerprinting: true

  label:
    text: "Home"
    icon: /favicon.ico
    iconHeight: 35
  
  homeInfoParams:
    Title: "Welcome to Opt Out Podcast \U0001F44B"
    Content: >
      - Opt Out is a podcast where I sit down with passionate people to learn why privacy matters to them, the tools and techniques they’ve found and leveraged, and where we encourage and inspire others towards personal privacy and data-sovereignty.
      
      -

      - Thanks in advance for listening, and I hope you learn as much as I do each episode!

      -

      - ***Jump into the latest episode directly below:***

      -


      <div id="buzzsprout-player-9966328"></div><script src="https://www.buzzsprout.com/1790481/9966328-network-privacy-via-tor-w-isabela-bagueros-from-the-tor-project.js?container_id=buzzsprout-player-9966328&player=small" type="text/javascript" charset="utf-8"></script>


  socialIcons:
    - name: rss
      url: "https://feeds.buzzsprout.com/1790481.rss"
    - name: applepodcasts
      url: "https://podcasts.apple.com/us/podcast/id1572450110?mt=2&ls=1"
    - name: spotify
      url: "https://open.spotify.com/show/59fX0wRUKhWGK9IAKt7bQM"
    - name: googlepodcasts
      url: "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5idXp6c3Byb3V0LmNvbS8xNzkwNDgxLnJzcw=="
    - name: pocketcasts
      url: "https://pca.st/3iu4ight"
    - name: overcast
      url: "https://overcast.fm/itunes1572450110"
    - name: youtube
      url: "https://www.youtube.com/c/OptOutPodcast"
    - name: peertube
      url: "https://videos.optoutpod.com"
    - name: twitter
      url: "https://twitter.com/optoutpod"
    - name: reddit
      url: "https://www.reddit.com/r/optoutpod/"
    - name: email
      url: "mailto:seth@optoutpod.com"
    - name: matrix
      url: "https://matrix.to/#/#optout:monero.social"
    - name: monero
      url: "https://optoutpod.com/about/#monero"
    - name: bitcoin
      url: "https://optoutpod.com/about/#bitcoin"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: episodes
      name: Episodes
      url: /episodes
      weight: 1
    - identifier: guests
      name: Guests
      url: /guests
      weight: 2
    - identifier: posts
      name: Blog Posts
      url: /posts
      weight: 3
    - identifier: about
      name: About
      url: /about
      weight: 4
    - identifier: sponsors
      name: Sponsors
      url: /sponsors
      weight: 5
    - identifier: search
      name: Search
      url: /search
      weight: 6

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: false
    enableDNT: false
    simple: true
  vimeo:
    disable: true
  youtube:
    disable: true
markup:
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    # noClasses: false
    style: solarized-dark
